### ISSUE TITLE
How to make unbound work without forward zone?

### ISSUE THREAD

**Issue by Dpoint1** [DesktopECHO/Pi-hole-for-Android#62]
Hi! I noticed that in the default unbound configuration file (pihole.conf) that it is forwarding to quad9 and cloudflare servers.
When i try to use the unbound configuration from [pihole website](https://docs.pi-hole.net/guides/dns/unbound/), unbound doesn't work.

Pihole unbound configuration:
```
server:
    # If no logfile is specified, syslog is used
    # logfile: "/var/log/unbound/unbound.log"
    verbosity: 0

    interface: 127.0.0.1
    port: 5335
    do-ip4: yes
    do-udp: yes
    do-tcp: yes

    # May be set to yes if you have IPv6 connectivity
    do-ip6: no

    # You want to leave this to no unless you have *native* IPv6. With 6to4 and
    # Terredo tunnels your web browser should favor IPv4 for the same reasons
    prefer-ip6: no

    # Use this only when you downloaded the list of primary root servers!
    # If you use the default dns-root-data package, unbound will find it automatically
    #root-hints: "/var/lib/unbound/root.hints"

    # Trust glue only if it is within the server's authority
    harden-glue: yes

    # Require DNSSEC data for trust-anchored zones, if such data is absent, the zone becomes BOGUS
    harden-dnssec-stripped: yes

    # Don't use Capitalization randomization as it known to cause DNSSEC issues sometimes
    # see https://discourse.pi-hole.net/t/unbound-stubby-or-dnscrypt-proxy/9378 for further details
    use-caps-for-id: no

    # Reduce EDNS reassembly buffer size.
    # IP fragmentation is unreliable on the Internet today, and can cause
    # transmission failures when large DNS messages are sent via UDP. Even
    # when fragmentation does work, it may not be secure; it is theoretically
    # possible to spoof parts of a fragmented DNS message, without easy
    # detection at the receiving end. Recently, there was an excellent study
    # >>> Defragmenting DNS - Determining the optimal maximum UDP response size for DNS <<<
    # by Axel Koolhaas, and Tjeerd Slokker (https://indico.dns-oarc.net/event/36/contributions/776/)
    # in collaboration with NLnet Labs explored DNS using real world data from the
    # the RIPE Atlas probes and the researchers suggested different values for
    # IPv4 and IPv6 and in different scenarios. They advise that servers should
    # be configured to limit DNS messages sent over UDP to a size that will not
    # trigger fragmentation on typical network links. DNS servers can switch
    # from UDP to TCP when a DNS response is too big to fit in this limited
    # buffer size. This value has also been suggested in DNS Flag Day 2020.
    edns-buffer-size: 1232

    # Perform prefetching of close to expired message cache entries
    # This only applies to domains that have been frequently queried
    prefetch: yes

    # One thread should be sufficient, can be increased on beefy machines. In reality for most users running on small networks or on a single machine, it should be unnecessary to seek performance enhancement by increasing num-threads above 1.
    num-threads: 1

    # Ensure kernel buffer is large enough to not lose messages in traffic spikes
    so-rcvbuf: 1m

    # Ensure privacy of local IP ranges
    private-address: 192.168.0.0/16
    private-address: 169.254.0.0/16
    private-address: 172.16.0.0/12
    private-address: 10.0.0.0/8
    private-address: fd00::/8
    private-address: fe80::/10
```
default config:
```
server:
        access-control: 127.0.0.0/8 allow
        cache-max-ttl: 14400
        cache-min-ttl: 600
        do-tcp: yes
        hide-identity: yes
        hide-version: yes
        interface: 127.0.0.1
        minimal-responses: yes
        prefetch: yes
        qname-minimisation: yes
        rrset-roundrobin: yes
        ssl-upstream: yes
        use-caps-for-id: yes
        verbosity: 1
        port: 5335

forward-zone:
        name: "."
        forward-addr: 9.9.9.9@853 # quad9.net primary
        forward-addr: 1.1.1.1@853 # cloudflare primary
        forward-addr: 149.112.112.112@853 # quad9.net secondary
        forward-addr: 1.0.0.1@853 # cloudflare secondary
```
I also tried using the root hints file, still doesn't work

Is there any way to make unbound work without forwarding to quad9 and cloudflare or any other dns server?

**Comment by virt-god** [comment]
I used the default  config, but commented out all forwarders. Seems to be working.

![Screenshot 2023-06-14 at 05-52-44 Pi-hole - perry](https://github.com/DesktopECHO/Pi-hole-for-Android/assets/121334908/2bab82b4-7494-4cdf-8072-57556b0f62fb)

```
server:
        access-control: 127.0.0.0/8 allow
        cache-max-ttl: 14400
        cache-min-ttl: 600
        do-tcp: yes
        hide-identity: yes
        hide-version: yes
        interface: 127.0.0.1
        minimal-responses: yes
        prefetch: yes
        qname-minimisation: yes
        rrset-roundrobin: yes
        ssl-upstream: yes
        use-caps-for-id: yes
        verbosity: 1
        port: 5335

#forward-zone:
#        name: "."
#        forward-addr: 9.9.9.9@853 # quad9.net primary
#        forward-addr: 1.1.1.1@853 # cloudflare primary
#        forward-addr: 149.112.112.112@853 # quad9.net secondary
#        forward-addr: 1.0.0.1@853 # cloudflare secondary
```

**Comment by Dpoint1** [comment]
I don't think that is working the reply is N/A

**Comment by virt-god** [comment]
@Dpoint1 
You were right was not working. I did not notice as I am just using this as a backup.
This one works. (changed verbosity to 1 so we can see logs)

![pitest](https://github.com/DesktopECHO/Pi-hole-for-Android/assets/121334908/d36a47da-792e-4f0b-83e5-7459548e4c22)

```
server:
        access-control: 127.0.0.0/8 allow
#        cache-max-ttl: 14400
#        cache-min-ttl: 600
        do-tcp: yes
        do-ip4: yes
        do-udp: yes
        hide-identity: yes
        hide-version: yes
        interface: 127.0.0.1
#        minimal-responses: yes
        prefetch: yes
#        qname-minimisation: yes
#        rrset-roundrobin: yes
#        ssl-upstream: yes
#        use-caps-for-id: yes
        verbosity: 1
        port: 5335
    # May be set to yes if you have IPv6 connectivity
        do-ip6: no
    # You want to leave this to no unless you have *native* IPv6. With 6to4 and
    # Terredo tunnels your web browser should favor IPv4 for the same reasons
        prefer-ip6: no
    # Trust glue only if it is within the server's authority
        harden-glue: yes
    # Require DNSSEC data for trust-anchored zones, if such data is absent, the zone becomes BOGUS
        harden-dnssec-stripped: yes
    # Don't use Capitalization randomization as it known to cause DNSSEC issues sometimes
    # see https://discourse.pi-hole.net/t/unbound-stubby-or-dnscrypt-proxy/9378 for further details
        use-caps-for-id: no
    # Reduce EDNS reassembly buffer size.
    # IP fragmentation is unreliable on the Internet today, and can cause
    # transmission failures when large DNS messages are sent via UDP. Even
    # when fragmentation does work, it may not be secure; it is theoretically
    # possible to spoof parts of a fragmented DNS message, without easy
    # detection at the receiving end. Recently, there was an excellent study
    # >>> Defragmenting DNS - Determining the optimal maximum UDP response size for DNS <<<
    # by Axel Koolhaas, and Tjeerd Slokker (https://indico.dns-oarc.net/event/36/contributions/776/)
    # in collaboration with NLnet Labs explored DNS using real world data from the
    # the RIPE Atlas probes and the researchers suggested different values for
    # IPv4 and IPv6 and in different scenarios. They advise that servers should
    # be configured to limit DNS messages sent over UDP to a size that will not
    # trigger fragmentation on typical network links. DNS servers can switch
    # from UDP to TCP when a DNS response is too big to fit in this limited
    # buffer size. This value has also been suggested in DNS Flag Day 2020.
        edns-buffer-size: 1232
        so-rcvbuf: 1m
```
